# Generated by Django 3.0.3 on 2020-09-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketid', models.CharField(max_length=20)),
                ('noofadult', models.CharField(max_length=20)),
                ('noofchild', models.CharField(max_length=20)),
                ('adultunitprice', models.CharField(max_length=10)),
                ('childunitprice', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tblTicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickettype', models.CharField(max_length=70)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
