# Generated by Django 3.0.3 on 2020-09-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblticket',
            name='postingdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
